CREATE TABLE IF NOT EXISTS front(
    front_id SERIAL PRIMARY KEY,
    content VARCHAR(2000) UNIQUE NOT NULL,
    card_id INTEGER NOT NULL,
    CONSTRAINT front_card_fk FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE
);